# Vocabulary lists for each level (100 words per level)
beginner_words = [
    {'word': 'hello', 'definition': 'used as a greeting', 'example': 'Hello, how are you today?'},
    {'word': 'goodbye', 'definition': 'used when leaving or ending a conversation', 'example': 'I have to go now, goodbye!'},
    {'word': 'water', 'definition': 'a clear liquid that falls as rain', 'example': 'Could I have a glass of water, please?'},
    {'word': 'friend', 'definition': 'a person you know well and like', 'example': 'She is my best friend from school.'},
    {'word': 'family', 'definition': 'a group of people who are related', 'example': 'I will visit my family this weekend.'},
    {'word': 'house', 'definition': 'a building where people live', 'example': 'They moved into a new house last month.'},
    {'word': 'thank you', 'definition': 'used to express gratitude', 'example': 'Thank you for helping me with my homework.'},
    {'word': 'please', 'definition': 'used when asking for something politely', 'example': 'Please pass me the salt.'},
    {'word': 'sorry', 'definition': 'used to apologize', 'example': "I'm sorry for being late."},
    {'word': 'food', 'definition': 'things that people eat', 'example': 'This restaurant serves delicious food.'},
    {'word': 'school', 'definition': 'a place where children go to learn', 'example': 'My brother goes to school every day.'},
    {'word': 'teacher', 'definition': 'a person who teaches', 'example': 'Our teacher is very kind.'},
    {'word': 'student', 'definition': 'a person who is learning', 'example': 'The student asked a question.'},
    {'word': 'book', 'definition': 'a set of written pages', 'example': 'I am reading a new book.'},
    {'word': 'pen', 'definition': 'an instrument for writing', 'example': 'Can I borrow your pen?'},
    {'word': 'car', 'definition': 'a road vehicle with an engine', 'example': 'My father drives a car.'},
    {'word': 'bus', 'definition': 'a large vehicle for many passengers', 'example': 'We took the bus to the city.'},
    {'word': 'city', 'definition': 'a large town', 'example': 'Tehran is a big city.'},
    {'word': 'country', 'definition': 'a nation with its own government', 'example': 'Iran is my country.'},
    {'word': 'street', 'definition': 'a public road in a city or town', 'example': 'There are many cars on the street.'},
    {'word': 'market', 'definition': 'a place where people buy and sell things', 'example': 'My mother goes to the market every week.'},
    {'word': 'shop', 'definition': 'a place where you can buy things', 'example': 'I bought a shirt from the shop.'},
    {'word': 'money', 'definition': 'coins or notes used to buy things', 'example': 'How much money do you have?'},
    {'word': 'phone', 'definition': 'a device for talking to people far away', 'example': 'She called me on the phone.'},
    {'word': 'computer', 'definition': 'an electronic machine for storing and processing data', 'example': 'I use my computer for work.'},
    {'word': 'internet', 'definition': 'a global network connecting millions of computers', 'example': 'I found the information on the internet.'},
    {'word': 'music', 'definition': 'sounds that are sung or played', 'example': 'I like listening to music.'},
    {'word': 'movie', 'definition': 'a story shown on a screen', 'example': 'We watched a movie last night.'},
    {'word': 'game', 'definition': 'an activity for fun', 'example': "Let's play a game."},
    {'word': 'ball', 'definition': 'a round object used in games', 'example': 'The children are playing with a ball.'},
    {'word': 'cat', 'definition': 'a small animal with fur', 'example': 'The cat is sleeping on the sofa.'},
    {'word': 'dog', 'definition': 'a common animal kept as a pet', 'example': 'My dog likes to run.'},
    {'word': 'bird', 'definition': 'an animal with feathers and wings', 'example': 'A bird is singing in the tree.'},
    {'word': 'tree', 'definition': 'a tall plant with a trunk and branches', 'example': 'There is a big tree in our garden.'},
    {'word': 'flower', 'definition': 'the colored part of a plant', 'example': 'She gave me a flower.'},
    {'word': 'sun', 'definition': 'the star that gives us light and heat', 'example': 'The sun is shining.'},
    {'word': 'moon', 'definition': 'the object that shines at night', 'example': 'The moon is full tonight.'},
    {'word': 'star', 'definition': 'a bright point in the night sky', 'example': 'There are many stars in the sky.'},
    {'word': 'sky', 'definition': 'the space above the earth', 'example': 'The sky is blue.'},
    {'word': 'rain', 'definition': 'water that falls from clouds', 'example': 'It is going to rain today.'},
    {'word': 'snow', 'definition': 'soft white pieces of frozen water', 'example': 'Children like to play in the snow.'},
    {'word': 'wind', 'definition': 'moving air', 'example': 'The wind is very strong.'},
    {'word': 'hot', 'definition': 'having a high temperature', 'example': 'The tea is hot.'},
    {'word': 'cold', 'definition': 'having a low temperature', 'example': 'It is cold in winter.'},
    {'word': 'happy', 'definition': 'feeling good', 'example': 'I am happy today.'},
    {'word': 'sad', 'definition': 'feeling unhappy', 'example': 'She is sad because her cat is lost.'},
    {'word': 'angry', 'definition': 'feeling strong dislike', 'example': 'He was angry about the mistake.'},
    {'word': 'tired', 'definition': 'needing rest', 'example': 'I am tired after work.'},
    {'word': 'hungry', 'definition': 'needing food', 'example': 'The baby is hungry.'},
    {'word': 'thirsty', 'definition': 'needing to drink', 'example': 'I am thirsty after running.'},
    {'word': 'sleep', 'definition': 'to rest with your eyes closed', 'example': "I sleep at 11 o'clock."},
    {'word': 'wake up', 'definition': 'to stop sleeping', 'example': 'I wake up at 7 a.m.'},
    {'word': 'eat', 'definition': 'to put food in your mouth and swallow it', 'example': 'We eat lunch at 1 p.m.'},
    {'word': 'drink', 'definition': 'to take liquid into your mouth and swallow it', 'example': 'She drinks water every morning.'},
    {'word': 'walk', 'definition': 'to move on foot', 'example': "Let's walk to the park."},
    {'word': 'run', 'definition': 'to move quickly on foot', 'example': 'He can run very fast.'},
    {'word': 'sit', 'definition': 'to be in a position in which your body is resting on a chair', 'example': 'Please sit down.'},
    {'word': 'stand', 'definition': 'to be in an upright position', 'example': 'Stand up, please.'},
    {'word': 'open', 'definition': 'to move something so that it is not closed', 'example': 'Open the window.'},
    {'word': 'close', 'definition': 'to move something so that it is not open', 'example': 'Close the door.'},
    {'word': 'start', 'definition': 'to begin', 'example': "Let's start the lesson."},
    {'word': 'finish', 'definition': 'to end', 'example': 'We finish school at 2 p.m.'},
    {'word': 'read', 'definition': 'to look at and understand words', 'example': 'I read a book every night.'},
    {'word': 'write', 'definition': 'to form letters or words on paper', 'example': 'Write your name here.'},
    {'word': 'listen', 'definition': 'to pay attention to sound', 'example': 'Listen to the teacher.'},
    {'word': 'speak', 'definition': 'to say words', 'example': 'Can you speak English?'},
    {'word': 'ask', 'definition': 'to say something to get an answer', 'example': 'Ask your question.'},
    {'word': 'answer', 'definition': 'to say something in reply', 'example': 'Please answer the question.'},
    {'word': 'question', 'definition': 'something you ask to get information', 'example': 'I have a question.'},
    {'word': 'problem', 'definition': 'something that is difficult to deal with', 'example': 'We have a problem with the computer.'},
    {'word': 'solution', 'definition': 'a way to solve a problem', 'example': 'We found a solution.'},
    {'word': 'time', 'definition': 'what a clock measures', 'example': 'What time is it?'},
    {'word': 'day', 'definition': 'a period of 24 hours', 'example': 'Today is a sunny day.'},
    {'word': 'night', 'definition': 'the time when it is dark', 'example': 'I sleep at night.'},
    {'word': 'morning', 'definition': 'the early part of the day', 'example': 'Good morning!'},
    {'word': 'afternoon', 'definition': 'the part of the day after 12 p.m.', 'example': 'I study in the afternoon.'},
    {'word': 'evening', 'definition': 'the part of the day after the afternoon', 'example': 'We watch TV in the evening.'},
    {'word': 'week', 'definition': 'a period of seven days', 'example': 'There are seven days in a week.'},
    {'word': 'month', 'definition': 'a period of about four weeks', 'example': 'My birthday is next month.'},
    {'word': 'year', 'definition': 'a period of twelve months', 'example': 'Happy New Year!'},
    {'word': 'birthday', 'definition': 'the day you were born', 'example': 'My birthday is in May.'},
    {'word': 'name', 'definition': 'what a person is called', 'example': 'What is your name?'},
    {'word': 'age', 'definition': 'how old someone is', 'example': 'How old are you?'},
    {'word': 'color', 'definition': 'red, blue, green, etc.', 'example': 'What is your favorite color?'},
    {'word': 'big', 'definition': 'large in size', 'example': 'The elephant is big.'},
    {'word': 'small', 'definition': 'not big', 'example': 'The mouse is small.'},
    {'word': 'long', 'definition': 'not short', 'example': 'The river is long.'},
    {'word': 'short', 'definition': 'not long', 'example': 'He has short hair.'},
    {'word': 'old', 'definition': 'having lived for many years', 'example': 'My grandfather is old.'},
    {'word': 'young', 'definition': 'not old', 'example': 'The baby is young.'},
    {'word': 'new', 'definition': 'not old', 'example': 'I have a new bag.'},
    {'word': 'good', 'definition': 'of high quality', 'example': 'This is a good idea.'},
    {'word': 'bad', 'definition': 'not good', 'example': 'That was a bad answer.'},
    {'word': 'easy', 'definition': 'not difficult', 'example': 'This question is easy.'},
    {'word': 'difficult', 'definition': 'not easy', 'example': 'The test was difficult.'},
    {'word': 'clean', 'definition': 'not dirty', 'example': 'Wash your hands to keep them clean.'},
    {'word': 'dirty', 'definition': 'not clean', 'example': 'Your shoes are dirty.'},
    {'word': 'full', 'definition': 'containing as much as possible', 'example': 'The glass is full of water.'},
    {'word': 'empty', 'definition': 'containing nothing', 'example': 'The box is empty.'},
    {'word': 'left', 'definition': 'opposite of right', 'example': 'Turn left at the corner.'},
    {'word': 'right', 'definition': 'opposite of left', 'example': 'Your answer is right.'},
    {'word': 'up', 'definition': 'towards a higher place', 'example': 'Look up at the sky.'},
    {'word': 'down', 'definition': 'towards a lower place', 'example': 'Go down the stairs.'},
    {'word': 'in', 'definition': 'inside something', 'example': 'The keys are in the bag.'},
    {'word': 'out', 'definition': 'outside something', 'example': 'Go out and play.'},
    {'word': 'on', 'definition': 'touching a surface', 'example': 'The book is on the table.'},
    {'word': 'under', 'definition': 'below something', 'example': 'The cat is under the chair.'},
    {'word': 'with', 'definition': 'accompanied by', 'example': 'I go to school with my friend.'},
    {'word': 'without', 'definition': 'not having', 'example': "I can't live without music."},
    {'word': 'for', 'definition': 'used to show purpose', 'example': 'This gift is for you.'},
    {'word': 'from', 'definition': 'used to show the origin', 'example': 'I am from Iran.'},
    {'word': 'to', 'definition': 'used to show direction', 'example': 'Give this to your teacher.'},
    {'word': 'by', 'definition': 'used to show how something is done', 'example': 'We travel by bus.'},
    {'word': 'about', 'definition': 'on the subject of', 'example': 'Tell me about your family.'},
    {'word': 'because', 'definition': 'for the reason that', 'example': 'I am happy because I passed the exam.'},
    {'word': 'but', 'definition': 'used to show contrast', 'example': 'I like tea but not coffee.'},
    {'word': 'and', 'definition': 'used to connect words', 'example': 'My brother and I play football.'},
    {'word': 'or', 'definition': 'used to show a choice', 'example': 'Do you want tea or coffee?'},
    {'word': 'if', 'definition': 'used to show a condition', 'example': 'If it rains, we will stay home.'},
    {'word': 'when', 'definition': 'at what time', 'example': 'When is your birthday?'},
    {'word': 'where', 'definition': 'at what place', 'example': 'Where do you live?'},
    {'word': 'who', 'definition': 'what person', 'example': 'Who is your teacher?'},
    {'word': 'what', 'definition': 'used to ask for information', 'example': 'What is this?'},
    {'word': 'why', 'definition': 'for what reason', 'example': 'Why are you sad?'},
    {'word': 'how', 'definition': 'in what way', 'example': 'How do you go to school?'}
]

elementary_words = [
    {'word': 'address', 'definition': 'the details of where someone lives or works', 'example': 'What is your home address?'},
    {'word': 'afraid', 'definition': 'feeling fear', 'example': 'She is afraid of spiders.'},
    {'word': 'airport', 'definition': 'a place where airplanes take off and land', 'example': 'We arrived at the airport early.'},
    {'word': 'animal', 'definition': 'a living creature that is not a plant', 'example': 'The zoo has many different animals.'},
    {'word': 'apartment', 'definition': 'a set of rooms for living in, usually on one floor of a building', 'example': 'They live in a small apartment.'},
    {'word': 'arrive', 'definition': 'to reach a place', 'example': 'The train will arrive soon.'},
    {'word': 'art', 'definition': 'creative work such as painting or drawing', 'example': 'She loves modern art.'},
    {'word': 'autumn', 'definition': 'the season between summer and winter', 'example': 'The leaves fall in autumn.'},
    {'word': 'bank', 'definition': 'a place where you keep or borrow money', 'example': 'I need to go to the bank.'},
    {'word': 'bathroom', 'definition': 'a room with a bath or shower and usually a toilet', 'example': 'The bathroom is upstairs.'},
    {'word': 'beach', 'definition': 'an area of sand or small stones by the sea', 'example': 'We swam at the beach.'},
    {'word': 'beautiful', 'definition': 'very attractive or pleasing', 'example': 'The garden is beautiful in spring.'},
    {'word': 'bedroom', 'definition': 'a room for sleeping in', 'example': 'My bedroom is next to the kitchen.'},
    {'word': 'begin', 'definition': 'to start doing something', 'example': "Let's begin the lesson."},
    {'word': 'bicycle', 'definition': 'a vehicle with two wheels that you ride by pushing pedals', 'example': 'He rides his bicycle to school.'},
    {'word': 'birthday', 'definition': 'the day you were born', 'example': 'Her birthday is in July.'},
    {'word': 'black', 'definition': 'the color of coal or the night sky', 'example': 'He wore a black shirt.'},
    {'word': 'blue', 'definition': 'the color of the sky on a clear day', 'example': 'She has blue eyes.'},
    {'word': 'breakfast', 'definition': 'the first meal of the day', 'example': 'We had eggs for breakfast.'},
    {'word': 'bridge', 'definition': 'a structure built over a river or road', 'example': 'The bridge crosses the river.'},
    {'word': 'bring', 'definition': 'to take something or someone with you', 'example': 'Please bring your book.'},
    {'word': 'building', 'definition': 'a structure with walls and a roof', 'example': 'That building is very tall.'},
    {'word': 'busy', 'definition': 'having a lot to do', 'example': 'My father is always busy.'},
    {'word': 'cafe', 'definition': 'a small restaurant where you can buy drinks and snacks', 'example': 'Lets meet at the cafe.'},
    {'word': 'camera', 'definition': 'a device for taking photographs', 'example': 'He bought a new camera.'},
    {'word': 'capital', 'definition': 'the most important city in a country', 'example': 'London is the capital of England.'},
    {'word': 'carry', 'definition': 'to hold something and take it somewhere', 'example': 'Can you carry this bag?'},
    {'word': 'center', 'definition': 'the middle of something', 'example': 'The park is in the center of the city.'},
    {'word': 'change', 'definition': 'to make or become different', 'example': 'I want to change my clothes.'},
    {'word': 'child', 'definition': 'a young person', 'example': 'The child is playing outside.'},
    {'word': 'choose', 'definition': 'to decide which thing you want', 'example': 'Choose your favorite color.'},
    {'word': 'cinema', 'definition': 'a place where you watch movies', 'example': 'We went to the cinema last night.'},
    {'word': 'clean', 'definition': 'to make something not dirty', 'example': 'Please clean your room.'},
    {'word': 'climb', 'definition': 'to go up something', 'example': 'They climb the mountain every year.'},
    {'word': 'clothes', 'definition': 'things you wear', 'example': 'She bought new clothes.'},
    {'word': 'cloud', 'definition': 'a white or gray mass in the sky', 'example': 'There is a big cloud above us.'},
    {'word': 'coat', 'definition': 'a piece of clothing you wear over other clothes', 'example': "Wear your coat, it's cold."},
    {'word': 'coffee', 'definition': 'a hot drink made from roasted beans', 'example': 'He drinks coffee every morning.'},
    {'word': 'cook', 'definition': 'to prepare food by heating it', 'example': 'She likes to cook dinner.'},
    {'word': 'corner', 'definition': 'the place where two lines or surfaces meet', 'example': 'The shop is on the corner.'},
    {'word': 'country', 'definition': 'an area of land with its own government', 'example': 'France is a beautiful country.'},
    {'word': 'cousin', 'definition': 'the child of your aunt or uncle', 'example': 'My cousin lives in Canada.'},
    {'word': 'crowd', 'definition': 'a large group of people', 'example': 'A crowd waited for the singer.'},
    {'word': 'dangerous', 'definition': 'likely to cause harm', 'example': 'It is dangerous to swim here.'},
    {'word': 'dark', 'definition': 'with little or no light', 'example': 'It gets dark at 6 p.m.'},
    {'word': 'date', 'definition': 'a particular day of the month or year', 'example': "What is today's date?"},
    {'word': 'daughter', 'definition': 'a female child', 'example': 'Their daughter is five years old.'},
    {'word': 'decide', 'definition': 'to make a choice', 'example': "I can't decide what to eat."},
    {'word': 'delicious', 'definition': 'very tasty', 'example': 'The cake is delicious.'},
    {'word': 'dentist', 'definition': 'a doctor who cares for teeth', 'example': 'I have an appointment with the dentist.'},
    {'word': 'describe', 'definition': 'to say what something is like', 'example': 'Can you describe your house?'},
    {'word': 'dictionary', 'definition': 'a book with words and their meanings', 'example': 'Look it up in the dictionary.'},
    {'word': 'different', 'definition': 'not the same', 'example': 'My bag is different from yours.'},
    {'word': 'dinner', 'definition': 'the main meal of the day', 'example': 'We have dinner at 7 p.m.'},
    {'word': 'doctor', 'definition': 'a person who treats sick people', 'example': 'The doctor gave me medicine.'},
    {'word': 'downstairs', 'definition': 'on or to a lower floor', 'example': 'The kitchen is downstairs.'},
    {'word': 'draw', 'definition': 'to make a picture with a pen or pencil', 'example': 'She can draw very well.'},
    {'word': 'dress', 'definition': 'a piece of clothing for women or girls', 'example': 'She wore a red dress.'},
    {'word': 'drive', 'definition': 'to control a car or other vehicle', 'example': 'He can drive a truck.'},
    {'word': 'dry', 'definition': 'not wet', 'example': 'Hang your clothes to dry.'},
    {'word': 'early', 'definition': 'before the usual time', 'example': 'He gets up early every day.'},
    {'word': 'east', 'definition': 'the direction where the sun rises', 'example': 'The sun rises in the east.'},
    {'word': 'easy', 'definition': 'not difficult', 'example': 'This exercise is easy.'},
    {'word': 'education', 'definition': 'the process of learning', 'example': 'Education is important for everyone.'},
    {'word': 'egg', 'definition': 'a round object from a bird, eaten as food', 'example': 'I had an egg for breakfast.'},
    {'word': 'electric', 'definition': 'using electricity', 'example': 'We bought an electric car.'},
    {'word': 'elephant', 'definition': 'a very large gray animal with a trunk', 'example': 'The elephant is the largest land animal.'},
    {'word': 'enjoy', 'definition': 'to get pleasure from something', 'example': 'I enjoy reading books.'},
    {'word': 'enough', 'definition': 'as much as you need', 'example': 'Do you have enough money?'},
    {'word': 'environment', 'definition': 'the natural world', 'example': 'We must protect the environment.'},
    {'word': 'excited', 'definition': 'very happy and interested', 'example': 'The children are excited about the trip.'},
    {'word': 'expensive', 'definition': 'costing a lot of money', 'example': 'This watch is very expensive.'},
    {'word': 'face', 'definition': 'the front part of your head', 'example': 'She washed her face.'},
    {'word': 'fall', 'definition': 'to move down quickly', 'example': 'Be careful not to fall.'},
    {'word': 'family', 'definition': 'a group of people who are related', 'example': 'My family is very important to me.'},
    {'word': 'famous', 'definition': 'known by many people', 'example': 'He is a famous actor.'},
    {'word': 'farm', 'definition': 'land used for growing crops or raising animals', 'example': 'They live on a farm.'},
    {'word': 'fast', 'definition': 'moving quickly', 'example': 'Cheetahs are very fast.'},
    {'word': 'favorite', 'definition': 'liked more than others', 'example': 'Blue is my favorite color.'},
    {'word': 'festival', 'definition': 'a special time or event for celebration', 'example': 'The music festival is in August.'},
    {'word': 'field', 'definition': 'an area of land for growing crops or playing sports', 'example': 'The cows are in the field.'},
    {'word': 'fight', 'definition': 'to use force to try to hurt someone', 'example': 'The boys started to fight.'},
    {'word': 'fill', 'definition': 'to make something full', 'example': 'Fill the glass with water.'},
    {'word': 'find', 'definition': 'to discover something', 'example': 'Can you find my keys?'},
    {'word': 'finish', 'definition': 'to end something', 'example': 'Please finish your homework.'},
    {'word': 'fire', 'definition': 'something that burns and gives heat and light', 'example': 'The fire kept us warm.'},
    {'word': 'fish', 'definition': 'an animal that lives in water', 'example': 'We saw many fish in the lake.'},
    {'word': 'floor', 'definition': 'the flat surface you walk on in a room', 'example': 'The floor is clean.'},
    {'word': 'flower', 'definition': 'the colored part of a plant', 'example': 'She picked a flower.'},
    {'word': 'follow', 'definition': 'to go after someone or something', 'example': 'Follow me, please.'},
    {'word': 'food', 'definition': 'things that people eat', 'example': 'We bought food for the picnic.'},
    {'word': 'forest', 'definition': 'a large area with many trees', 'example': 'The forest is very quiet.'},
    {'word': 'forget', 'definition': 'to not remember', 'example': 'Don\'t forget your umbrella.'},
    {'word': 'free', 'definition': 'not costing any money', 'example': 'The tickets are free.'},
    {'word': 'fresh', 'definition': 'new or not old', 'example': 'I like fresh bread.'},
    {'word': 'fridge', 'definition': 'a machine for keeping food cold', 'example': 'Put the milk in the fridge.'},
    {'word': 'friendly', 'definition': 'kind and pleasant', 'example': 'Our neighbors are very friendly.'},
    {'word': 'fruit', 'definition': 'food that grows on trees or plants', 'example': 'Bananas are my favorite fruit.'},
    {'word': 'future', 'definition': 'the time that will come after now', 'example': 'What are your plans for the future?'},
    {'word': 'garden', 'definition': 'a piece of land for growing flowers or vegetables', 'example': 'We have a small garden.'},
    {'word': 'gift', 'definition': 'something you give to someone', 'example': 'She gave me a birthday gift.'},
    {'word': 'glass', 'definition': 'a container for drinking', 'example': 'He drank a glass of water.'},
    {'word': 'glasses', 'definition': 'lenses worn to help you see better', 'example': 'She wears glasses to read.'},
    {'word': 'glove', 'definition': 'a piece of clothing for the hand', 'example': 'Wear your gloves, it\'s cold.'},
    {'word': 'gold', 'definition': 'a yellow precious metal', 'example': 'The ring is made of gold.'},
    {'word': 'goodbye', 'definition': 'used when leaving', 'example': 'Say goodbye to your friends.'},
    {'word': 'grandfather', 'definition': 'the father of your father or mother', 'example': 'My grandfather tells great stories.'},
    {'word': 'grandmother', 'definition': 'the mother of your father or mother', 'example': 'Her grandmother is 80 years old.'},
    {'word': 'group', 'definition': 'a number of people or things together', 'example': 'We worked in a group.'},
    {'word': 'grow', 'definition': 'to become bigger or older', 'example': 'Children grow quickly.'},
    {'word': 'guess', 'definition': 'to try to give an answer without being sure', 'example': 'Can you guess my age?'},
    {'word': 'guest', 'definition': 'a person who is invited to visit', 'example': 'We have a guest for dinner.'},
    {'word': 'hair', 'definition': 'the thin threads that grow on your head', 'example': 'She has long hair.'},
    {'word': 'half', 'definition': 'one of two equal parts', 'example': 'Cut the apple in half.'},
    {'word': 'hall', 'definition': 'a large room or building for meetings', 'example': 'The concert is in the main hall.'},
    {'word': 'hand', 'definition': 'the part of your body at the end of your arm', 'example': 'Wash your hands before eating.'},
    {'word': 'happen', 'definition': 'to take place', 'example': 'What will happen next?'},
    {'word': 'happy', 'definition': 'feeling good', 'example': 'She is happy with her new job.'},
    {'word': 'hard', 'definition': 'difficult to do or understand', 'example': 'This question is hard.'},
    {'word': 'hat', 'definition': 'something you wear on your head', 'example': 'He wore a black hat.'},
    {'word': 'health', 'definition': 'the condition of your body', 'example': 'Exercise is good for your health.'},
    {'word': 'hear', 'definition': 'to be aware of sound with your ears', 'example': 'Can you hear the music?'},
    {'word': 'heart', 'definition': 'the organ that pumps blood', 'example': 'The heart is very important.'},
    {'word': 'heavy', 'definition': 'having a lot of weight', 'example': 'This box is heavy.'},
    {'word': 'hello', 'definition': 'used as a greeting', 'example': 'Hello, how are you?'},
    {'word': 'help', 'definition': 'to make it easier for someone to do something', 'example': 'Can you help me with this?'},
    {'word': 'high', 'definition': 'a great distance from top to bottom', 'example': 'The mountain is very high.'},
    {'word': 'history', 'definition': 'the study of past events', 'example': 'We learned about history in school.'},
    {'word': 'holiday', 'definition': 'a time when you do not have to work or go to school', 'example': 'We went to the beach on holiday.'},
    {'word': 'homework', 'definition': 'work that a student does at home', 'example': 'I finished my homework.'},
    {'word': 'hope', 'definition': 'to want something to happen', 'example': 'I hope you feel better soon.'},
    {'word': 'hospital', 'definition': 'a place where sick people are treated', 'example': 'She works at the hospital.'},
    {'word': 'hotel', 'definition': 'a building where you pay to stay when away from home', 'example': 'We stayed at a nice hotel.'},
    {'word': 'hour', 'definition': 'a period of 60 minutes', 'example': 'The lesson is one hour long.'},
    {'word': 'hungry', 'definition': 'needing food', 'example': 'I am hungry after school.'},
    {'word': 'hurry', 'definition': 'to do something quickly', 'example': "Hurry up or we'll be late."},
    {'word': 'ice', 'definition': 'frozen water', 'example': 'The lake is covered with ice.'},
    {'word': 'idea', 'definition': 'a thought or suggestion', 'example': "That's a good idea."},
    {'word': 'important', 'definition': 'having great meaning or value', 'example': 'It is important to study.'},
    {'word': 'improve', 'definition': 'to make something better', 'example': 'You can improve your English.'},
    {'word': 'include', 'definition': 'to have as a part', 'example': 'The price includes breakfast.'},
    {'word': 'information', 'definition': 'facts or details about something', 'example': 'Can you give me more information?'},
    {'word': 'inside', 'definition': 'in or into a room, building, or container', 'example': 'The cat is inside the house.'},
    {'word': 'invite', 'definition': 'to ask someone to come to an event', 'example': 'Did you invite your friends?'},
    {'word': 'island', 'definition': 'a piece of land surrounded by water', 'example': 'They live on a small island.'},
    {'word': 'jacket', 'definition': 'a short coat', 'example': 'Wear your jacket, it\'s cold.'},   
    {'word': 'job', 'definition': 'the work that a person does', 'example': 'He has a new job.'},
    {'word': 'join', 'definition': 'to become a member of a group', 'example': 'Would you like to join our club?'},
    {'word': 'journey', 'definition': 'the act of traveling from one place to another', 'example': 'The journey took three hours.'},
    {'word': 'juice', 'definition': 'the liquid from fruit or vegetables', 'example': 'Would you like some orange juice?'},
    {'word': 'jump', 'definition': 'to push yourself off the ground and into the air', 'example': 'The children jump over the rope.'},
    {'word': 'key', 'definition': 'a small piece of metal used to open locks', 'example': 'I lost my house key.'},
    {'word': 'kitchen', 'definition': 'a room where food is prepared', 'example': 'The kitchen smells good.'},
    {'word': 'lake', 'definition': 'a large area of water surrounded by land', 'example': 'We swam in the lake.'},
    {'word': 'lamp', 'definition': 'a device for giving light', 'example': 'Turn on the lamp, please.'},
    {'word': 'language', 'definition': 'the words and grammar used by people to communicate', 'example': 'English is a global language.'},
    {'word': 'large', 'definition': 'big in size', 'example': 'They have a large house.'},
    {'word': 'last', 'definition': 'coming after all others', 'example': 'He was the last to arrive.'},
    {'word': 'late', 'definition': 'after the expected time', 'example': 'She is always late for class.'},
    {'word': 'laugh', 'definition': 'to make sounds with your voice when something is funny', 'example': 'The joke made everyone laugh.'},
    {'word': 'learn', 'definition': 'to get knowledge or skill', 'example': 'We learn new words every day.'},
    {'word': 'leave', 'definition': 'to go away from a place', 'example': 'I leave home at 8 a.m.'},
    {'word': 'left', 'definition': 'the opposite of right', 'example': 'Turn left at the traffic light.'},
    {'word': 'library', 'definition': 'a place where you can borrow books', 'example': 'The library is open until 6 p.m.'},
    {'word': 'light', 'definition': 'something that makes things visible', 'example': 'The light is very bright.'},
    {'word': 'listen', 'definition': 'to pay attention to sound', 'example': 'Listen to the music.'},
    {'word': 'living room', 'definition': 'a room in a house for relaxing', 'example': 'We watch TV in the living room.'},
    {'word': 'local', 'definition': 'relating to a particular area', 'example': 'Buy food from local shops.'},
    {'word': 'lose', 'definition': 'to not have something anymore', 'example': 'Don\'t lose your keys.'},
    {'word': 'loud', 'definition': 'making a lot of noise', 'example': 'The music is too loud.'},
    {'word': 'love', 'definition': 'to like someone or something very much', 'example': 'I love my family.'},
    {'word': 'lunch', 'definition': 'a meal eaten in the middle of the day', 'example': 'We had sandwiches for lunch.'},
    {'word': 'machine', 'definition': 'a piece of equipment with moving parts', 'example': 'The washing machine is broken.'},
    {'word': 'magazine', 'definition': 'a thin book with articles and pictures', 'example': 'She reads a fashion magazine.'},
    {'word': 'main', 'definition': 'most important', 'example': 'The main road is closed.'},
    {'word': 'make', 'definition': 'to create or produce something', 'example': 'Let\'s make a cake.'},
    {'word': 'manager', 'definition': 'a person who controls a business or part of a business', 'example': 'The manager is in his office.'},
    {'word': 'market', 'definition': 'a place where people buy and sell things', 'example': 'We went to the market.'},
    {'word': 'married', 'definition': 'having a husband or wife', 'example': 'My parents are married.'},
    {'word': 'material', 'definition': 'what something is made of', 'example': 'The dress is made of soft material.'},
    {'word': 'maybe', 'definition': 'possibly but not certainly', 'example': 'Maybe we will go out tonight.'},
    {'word': 'meal', 'definition': 'an occasion when you eat food', 'example': 'Breakfast is my favorite meal.'},
    {'word': 'medicine', 'definition': 'something you take to feel better when you are sick', 'example': 'Take your medicine after lunch.'},
    {'word': 'meet', 'definition': 'to see and talk to someone for the first time or after a long time', 'example': 'Let\'s meet at the park.'},
    {'word': 'message', 'definition': 'a piece of information sent to someone', 'example': 'I got your message.'},
    {'word': 'minute', 'definition': 'a period of 60 seconds', 'example': 'Wait a minute, please.'},
    {'word': 'mirror', 'definition': 'a piece of glass that reflects images', 'example': 'Look in the mirror.'},
    {'word': 'modern', 'definition': 'of the present time', 'example': 'They live in a modern house.'},
    {'word': 'moment', 'definition': 'a very short period of time', 'example': 'Wait a moment.'},
    {'word': 'money', 'definition': 'coins or notes used to buy things', 'example': 'How much money do you have?'},
    {'word': 'month', 'definition': 'a period of about four weeks', 'example': 'My birthday is next month.'},
    {'word': 'mountain', 'definition': 'a very high hill', 'example': 'We climbed the mountain.'},
    {'word': 'museum', 'definition': 'a building where you can look at important objects', 'example': 'The museum is free on Sundays.'},
    {'word': 'music', 'definition': 'sounds that are sung or played', 'example': 'She listens to music every day.'},
    {'word': 'nature', 'definition': 'everything in the world not made by people', 'example': 'We should protect nature.'},
    {'word': 'near', 'definition': 'not far away', 'example': 'The school is near my house.'},
    {'word': 'nearly', 'definition': 'almost', 'example': 'It\'s nearly time to go.'},
    {'word': 'neck', 'definition': 'the part of the body between the head and the shoulders', 'example': 'He wore a scarf around his neck.'},
    {'word': 'need', 'definition': 'to require something', 'example': 'I need some help.'},
    {'word': 'neighbor', 'definition': 'a person who lives near you', 'example': 'Our neighbor is very friendly.'},
    {'word': 'news', 'definition': 'information about recent events', 'example': 'Did you hear the news?'},
    {'word': 'newspaper', 'definition': 'a set of large printed sheets of paper with news', 'example': 'He reads the newspaper every morning.'},
    {'word': 'night', 'definition': 'the time when it is dark', 'example': 'I sleep at night.'},
    {'word': 'noise', 'definition': 'a sound, especially a loud one', 'example': 'There was a loud noise outside.'},
    {'word': 'north', 'definition': 'the direction opposite to south', 'example': 'Canada is to the north of the USA.'},
    {'word': 'notebook', 'definition': 'a book of blank pages for writing in', 'example': 'Write it in your notebook.'},
    {'word': 'nurse', 'definition': 'a person trained to care for sick people', 'example': 'The nurse gave me medicine.'},
    {'word': 'object', 'definition': 'a thing that you can see or touch', 'example': 'What is that object on the table?'},
    {'word': 'ocean', 'definition': 'a very large area of sea', 'example': 'The Pacific is the largest ocean.'},
    {'word': 'office', 'definition': 'a room or building where people work', 'example': 'My mother works in an office.'},
    {'word': 'often', 'definition': 'many times', 'example': 'I often go to the gym.'},
    {'word': 'opposite', 'definition': 'completely different', 'example': 'The opposite of hot is cold.'},
    {'word': 'order', 'definition': 'to ask for something in a restaurant or shop', 'example': 'I would like to order a pizza.'},
    {'word': 'outside', 'definition': 'not inside', 'example': 'Let\'s play outside.'},
    {'word': 'own', 'definition': 'belonging to yourself', 'example': 'I have my own room.'},
    {'word': 'paint', 'definition': 'to cover a surface with color', 'example': 'Let\'s paint the wall blue.'},
    {'word': 'pair', 'definition': 'two things that are the same and used together', 'example': 'I bought a new pair of shoes.'},
    {'word': 'parent', 'definition': 'a mother or father', 'example': 'My parents are teachers.'},
    {'word': 'park', 'definition': 'a public green area in a town', 'example': 'We walk in the park every evening.'},
    {'word': 'party', 'definition': 'a social event where people meet to celebrate', 'example': 'We had a party for her birthday.'},
    {'word': 'pass', 'definition': 'to go past something or someone', 'example': 'Pass me the salt, please.'},
    {'word': 'passenger', 'definition': 'a person who is traveling in a vehicle', 'example': 'There were ten passengers on the bus.'},
    {'word': 'past', 'definition': 'the time before now', 'example': 'We learned about the past in history class.'},
    {'word': 'pay', 'definition': 'to give money for something', 'example': 'I will pay for the tickets.'},
    {'word': 'pen', 'definition': 'an instrument for writing', 'example': 'Can I borrow your pen?'},
    {'word': 'pencil', 'definition': 'an instrument for writing or drawing', 'example': 'Sharpen your pencil.'},
    {'word': 'people', 'definition': 'men, women, and children', 'example': 'There are many people in the park.'},
    {'word': 'perfect', 'definition': 'without any mistakes', 'example': 'Her English is perfect.'},
    {'word': 'person', 'definition': 'a human being', 'example': 'He is a nice person.'},
    {'word': 'pet', 'definition': 'an animal kept for pleasure', 'example': 'They have a pet rabbit.'},
    {'word': 'phone', 'definition': 'a device for talking to people far away', 'example': 'She called me on the phone.'},
    {'word': 'photo', 'definition': 'a picture taken with a camera', 'example': 'Let\'s take a photo together.'},
    {'word': 'piano', 'definition': 'a large musical instrument with keys', 'example': 'She plays the piano.'},
    {'word': 'picture', 'definition': 'a painting, drawing, or photograph', 'example': 'There is a picture on the wall.'},
    {'word': 'piece', 'definition': 'a part of something', 'example': 'Can I have a piece of cake?'},
    {'word': 'place', 'definition': 'a particular area or position', 'example': 'This is a nice place.'},
    {'word': 'plan', 'definition': 'a set of actions for doing something', 'example': 'What is your plan for the weekend?'},
    {'word': 'plant', 'definition': 'a living thing that grows in the ground', 'example': 'Water the plant every day.'},
    {'word': 'play', 'definition': 'to do something for fun', 'example': 'The children play in the garden.'},
    {'word': 'please', 'definition': 'used to ask for something politely', 'example': 'Please open the window.'},
    {'word': 'pocket', 'definition': 'a small bag in your clothes', 'example': 'He put the money in his pocket.'},
    {'word': 'police', 'definition': 'the people who make sure laws are followed', 'example': 'The police helped us find our dog.'},
    {'word': 'pool', 'definition': 'a place filled with water for swimming', 'example': 'The hotel has a swimming pool.'},
    {'word': 'poor', 'definition': 'not having much money', 'example': 'They are a poor family.'},
    {'word': 'popular', 'definition': 'liked by many people', 'example': 'Soccer is a popular sport.'},
    {'word': 'post', 'definition': 'letters and parcels sent by mail', 'example': 'I got a letter in the post.'},
    {'word': 'potato', 'definition': 'a round vegetable with brown or yellow skin', 'example': 'We had potatoes for dinner.'},
    {'word': 'present', 'definition': 'something you give to someone on a special day', 'example': 'She got a present for her birthday.'},
    {'word': 'price', 'definition': 'the amount of money you pay for something', 'example': 'What is the price of this book?'},
    {'word': 'print', 'definition': 'to produce writing or images on paper', 'example': 'Can you print this document?'},
    {'word': 'problem', 'definition': 'something that is difficult to deal with', 'example': 'We have a problem with the car.'},
    {'word': 'program', 'definition': 'a set of instructions for a computer', 'example': 'He wrote a computer program.'},
    {'word': 'pull', 'definition': 'to use force to move something towards you', 'example': 'Pull the door to open it.'},
    {'word': 'push', 'definition': 'to use force to move something away from you', 'example': 'Push the button to start.'},
    {'word': 'question', 'definition': 'something you ask to get information', 'example': 'I have a question.'},
    {'word': 'quiet', 'definition': 'making very little noise', 'example': 'Be quiet in the library.'},
    {'word': 'rain', 'definition': 'water that falls from clouds', 'example': 'It might rain tomorrow.'},
    {'word': 'ready', 'definition': 'prepared for something', 'example': 'Are you ready to go?'},
    {'word': 'really', 'definition': 'in fact; actually', 'example': 'Do you really want to leave?'},
    {'word': 'reason', 'definition': 'the cause of something', 'example': 'What is the reason for your visit?'},
    {'word': 'receive', 'definition': 'to get something', 'example': 'Did you receive my email?'},
    {'word': 'remember', 'definition': 'to keep something in your mind', 'example': 'Remember to lock the door.'},
    {'word': 'repeat', 'definition': 'to say or do something again', 'example': 'Please repeat your answer.'},
    {'word': 'restaurant', 'definition': 'a place where you can buy and eat a meal', 'example': 'We had dinner at a restaurant.'},
    {'word': 'return', 'definition': 'to go or come back', 'example': 'When will you return home?'},
    {'word': 'rice', 'definition': 'a food that is small, white, and grows in water', 'example': 'We had rice and chicken for lunch.'},
    {'word': 'ride', 'definition': 'to sit on and control the movement of something', 'example': 'He can ride a horse.'},
    {'word': 'right', 'definition': 'the opposite of left', 'example': 'Turn right at the corner.'},
    {'word': 'river', 'definition': 'a large stream of water', 'example': 'The river flows to the sea.'},
    {'word': 'road', 'definition': 'a way for cars to travel', 'example': 'The road is very busy.'},
    {'word': 'room', 'definition': 'a part of a building with walls', 'example': 'My room is very small.'},
    {'word': 'round', 'definition': 'shaped like a circle', 'example': 'The table is round.'},
    {'word': 'rule', 'definition': 'an official instruction that says how things must be done', 'example': 'You must follow the rules.'},
    {'word': 'run', 'definition': 'to move quickly on foot', 'example': 'He can run very fast.'}
]

intermediate_words = [
    {'word': 'ability', 'definition': 'the power or skill to do something', 'example': 'She has the ability to solve problems quickly.'},
    {'word': 'achieve', 'definition': 'to succeed in doing something', 'example': 'He worked hard to achieve his goals.'},
    {'word': 'advice', 'definition': 'an opinion about what someone should do', 'example': 'She gave me good advice.'},
    {'word': 'affect', 'definition': 'to influence something', 'example': 'The weather can affect your mood.'},
    {'word': 'allow', 'definition': 'to let someone do something', 'example': 'My parents allow me to stay out late.'},
    {'word': 'amount', 'definition': 'a quantity of something', 'example': 'He ate a large amount of food.'},
    {'word': 'ancient', 'definition': 'very old', 'example': 'They visited ancient ruins.'},
    {'word': 'appear', 'definition': 'to become visible', 'example': 'A rainbow appeared after the rain.'},
    {'word': 'apply', 'definition': 'to make a formal request', 'example': 'She applied for a new job.'},
    {'word': 'argue', 'definition': 'to disagree or fight with words', 'example': 'They often argue about politics.'},
    {'word': 'arrange', 'definition': 'to organize or make plans for something', 'example': 'I will arrange a meeting for tomorrow.'},
    {'word': 'attempt', 'definition': 'to try to do something', 'example': 'He will attempt to break the record.'},
    {'word': 'attend', 'definition': 'to go to an event or place', 'example': 'She will attend the conference next week.'},
    {'word': 'average', 'definition': 'the usual or typical amount', 'example': 'The average temperature in July is 30°C.'},
    {'word': 'avoid', 'definition': 'to stay away from something', 'example': 'You should avoid eating too much sugar.'},
    {'word': 'balance', 'definition': 'a state where things are of equal weight or force', 'example': 'She lost her balance and fell.'},
    {'word': 'behavior', 'definition': 'the way someone acts', 'example': 'His behavior in class is excellent.'},
    {'word': 'benefit', 'definition': 'an advantage or profit', 'example': 'Exercise has many health benefits.'},
    {'word': 'challenge', 'definition': 'something difficult that requires effort', 'example': 'Climbing the mountain was a big challenge.'},
    {'word': 'character', 'definition': 'the qualities that make a person different from others', 'example': 'She has a kind character.'},
    {'word': 'community', 'definition': 'a group of people living in the same area', 'example': 'Our community is very friendly.'},
    {'word': 'compare', 'definition': 'to look for similarities and differences', 'example': 'Compare your answers with your partner.'},
    {'word': 'complain', 'definition': 'to say you are not satisfied with something', 'example': 'He always complains about the weather.'},
    {'word': 'complete', 'definition': 'to finish something', 'example': 'Please complete the form.'},
    {'word': 'concern', 'definition': 'a feeling of worry', 'example': 'There is growing concern about pollution.'},
    {'word': 'confirm', 'definition': 'to make sure something is true', 'example': 'Can you confirm your booking?'},
    {'word': 'confuse', 'definition': 'to make someone unable to think clearly', 'example': 'The instructions confused me.'},
    {'word': 'consequence', 'definition': 'a result of an action', 'example': 'His mistake had serious consequences.'},
    {'word': 'consider', 'definition': 'to think about something carefully', 'example': 'Please consider my suggestion.'},
    {'word': 'contain', 'definition': 'to have something inside', 'example': 'This box contains old photos.'},
    {'word': 'continue', 'definition': 'to keep doing something', 'example': 'We will continue after lunch.'},
    {'word': 'contribute', 'definition': 'to give something to help', 'example': 'Everyone contributed to the project.'},
    {'word': 'convince', 'definition': 'to make someone believe something', 'example': 'She convinced me to join the club.'},
    {'word': 'create', 'definition': 'to make something new', 'example': 'The artist created a beautiful painting.'},
    {'word': 'criticize', 'definition': 'to say what you think is wrong with something', 'example': 'He criticized my work.'},
    {'word': 'culture', 'definition': 'the ideas and customs of a group of people', 'example': 'We learned about Japanese culture.'},
    {'word': 'damage', 'definition': 'physical harm caused to something', 'example': 'The storm damaged the roof.'},
    {'word': 'decision', 'definition': 'a choice made after thinking', 'example': 'It was a difficult decision.'},
    {'word': 'decrease', 'definition': 'to become less', 'example': 'Sales decreased last year.'},
    {'word': 'define', 'definition': 'to explain the meaning of a word', 'example': 'Can you define this term?'},
    {'word': 'delay', 'definition': 'to make something happen later', 'example': 'The flight was delayed.'},
    {'word': 'depend', 'definition': 'to need the help of someone or something', 'example': 'Children depend on their parents.'},
    {'word': 'describe', 'definition': 'to say what something is like', 'example': 'Can you describe your hometown?'},
    {'word': 'deserve', 'definition': 'to be worthy of something', 'example': 'You deserve a reward for your hard work.'},
    {'word': 'develop', 'definition': 'to grow or change into something better', 'example': 'The company developed a new product.'},
    {'word': 'difference', 'definition': 'the way in which two things are not the same', 'example': 'There is a big difference between them.'},
    {'word': 'direct', 'definition': 'to control or guide', 'example': 'He directed the movie.'},
    {'word': 'discuss', 'definition': 'to talk about something with someone', 'example': 'Let\'s discuss the problem.'},
    {'word': 'distance', 'definition': 'the amount of space between two places', 'example': 'The distance between the cities is 100 km.'},
    {'word': 'divide', 'definition': 'to separate into parts', 'example': 'Divide the class into groups.'},
    {'word': 'doubt', 'definition': 'a feeling of not being sure', 'example': 'I have some doubts about his story.'},
    {'word': 'education', 'definition': 'the process of teaching and learning', 'example': 'Education is important for everyone.'},
    {'word': 'effect', 'definition': 'a change that is caused by something', 'example': 'The medicine had a strong effect.'},
    {'word': 'efficient', 'definition': 'doing something well without wasting time', 'example': 'She is an efficient worker.'},
    {'word': 'emphasize', 'definition': 'to give special importance to something', 'example': 'He emphasized the need for caution.'},
    {'word': 'encourage', 'definition': 'to give someone confidence to do something', 'example': 'My parents encouraged me to study.'},
    {'word': 'environment', 'definition': 'the natural world', 'example': 'We must protect the environment.'},
    {'word': 'error', 'definition': 'a mistake', 'example': 'There was an error in the report.'},
    {'word': 'escape', 'definition': 'to get away from a place', 'example': 'The prisoners tried to escape.'},
    {'word': 'essential', 'definition': 'very important and necessary', 'example': 'Water is essential for life.'},
    {'word': 'estimate', 'definition': 'to guess the size or amount of something', 'example': 'Can you estimate the cost?'},
    {'word': 'evidence', 'definition': 'facts that show something is true', 'example': 'There is no evidence against him.'},
    {'word': 'exact', 'definition': 'completely correct or accurate', 'example': 'What is the exact time?'},
    {'word': 'except', 'definition': 'not including', 'example': 'Everyone was there except John.'},
    {'word': 'exchange', 'definition': 'to give something and receive something else', 'example': 'They exchanged gifts at Christmas.'},
    {'word': 'expand', 'definition': 'to become larger', 'example': 'The company plans to expand.'},
    {'word': 'expect', 'definition': 'to think something will happen', 'example': 'I expect to see you soon.'},
    {'word': 'experience', 'definition': 'knowledge or skill from doing something', 'example': 'She has a lot of teaching experience.'},
    {'word': 'expert', 'definition': 'a person with special knowledge', 'example': 'He is an expert in computers.'},
    {'word': 'explain', 'definition': 'to make something clear or easy to understand', 'example': 'Can you explain this rule?'},
    {'word': 'explore', 'definition': 'to travel around a place to learn about it', 'example': 'They explored the island.'},
    {'word': 'express', 'definition': 'to show what you think or feel', 'example': 'He expressed his opinion.'},
    {'word': 'factor', 'definition': 'something that influences a result', 'example': 'Price is an important factor.'},
    {'word': 'familiar', 'definition': 'well known or easily recognized', 'example': 'Her face looks familiar.'},
    {'word': 'feature', 'definition': 'an important part of something', 'example': 'The new phone has many features.'},
    {'word': 'focus', 'definition': 'to give attention to something', 'example': 'Try to focus on your work.'},
    {'word': 'function', 'definition': 'the purpose of something', 'example': 'The function of the heart is to pump blood.'},
    {'word': 'goal', 'definition': 'something you want to achieve', 'example': 'Her goal is to become a doctor.'},
    {'word': 'habit', 'definition': 'something you do regularly', 'example': 'He has a habit of biting his nails.'},
    {'word': 'identify', 'definition': 'to recognize someone or something', 'example': 'Can you identify this animal?'},
    {'word': 'ignore', 'definition': 'to pay no attention to something', 'example': 'He ignored my advice.'},
    {'word': 'imagine', 'definition': 'to form a picture in your mind', 'example': 'Can you imagine living on the moon?'},
    {'word': 'improve', 'definition': 'to make something better', 'example': 'You can improve your English.'},
    {'word': 'include', 'definition': 'to have as a part', 'example': 'The price includes breakfast.'},
    {'word': 'indicate', 'definition': 'to show or point out', 'example': 'The sign indicates the right direction.'},
    {'word': 'individual', 'definition': 'a single person', 'example': 'Each individual is important.'},
    {'word': 'inform', 'definition': 'to give information', 'example': 'Please inform me of any changes.'},
    {'word': 'injure', 'definition': 'to hurt someone physically', 'example': 'He injured his leg while playing football.'},
    {'word': 'involve', 'definition': 'to include someone or something in an activity', 'example': 'The job involves a lot of travel.'},
    {'word': 'issue', 'definition': 'an important topic or problem', 'example': 'They discussed the issue at the meeting.'},
    {'word': 'knowledge', 'definition': 'information and understanding', 'example': 'He has a lot of knowledge about history.'},
    {'word': 'lack', 'definition': 'not having enough of something', 'example': 'There is a lack of water in the desert.'},
    {'word': 'limit', 'definition': 'the greatest amount allowed', 'example': 'There is a limit to how much you can carry.'},
    {'word': 'major', 'definition': 'very important', 'example': 'Pollution is a major problem.'},
    {'word': 'manage', 'definition': 'to control or be in charge of something', 'example': 'She manages a team of ten people.'},
    {'word': 'mention', 'definition': 'to talk about something briefly', 'example': 'He mentioned your name.'},
    {'word': 'method', 'definition': 'a way of doing something', 'example': 'This method is very effective.'},
    {'word': 'notice', 'definition': 'to see or become aware of something', 'example': 'Did you notice the mistake?'},
    {'word': 'object', 'definition': 'a thing that you can see or touch', 'example': 'What is that object on the table?'},
    {'word': 'occasion', 'definition': 'a special event or time', 'example': 'We met on several occasions.'},
    {'word': 'opinion', 'definition': 'what you think about something', 'example': 'What is your opinion about this movie?'},
    {'word': 'opportunity', 'definition': 'a chance to do something', 'example': 'This is a great opportunity for you.'},
    {'word': 'organize', 'definition': 'to arrange or plan things', 'example': 'She organized the party.'},
    {'word': 'participate', 'definition': 'to take part in something', 'example': 'Many students participated in the competition.'},
    {'word': 'patient', 'definition': 'able to wait calmly', 'example': 'You need to be patient with children.'},
    {'word': 'perform', 'definition': 'to do something, especially in front of people', 'example': 'The band will perform tonight.'},
    {'word': 'positive', 'definition': 'feeling good about something', 'example': 'Try to have a positive attitude.'},
    {'word': 'possibility', 'definition': 'something that might happen', 'example': 'There is a possibility of rain.'},
    {'word': 'prefer', 'definition': 'to like one thing more than another', 'example': 'I prefer tea to coffee.'},
    {'word': 'prepare', 'definition': 'to get ready for something', 'example': 'She prepared dinner for the family.'},
    {'word': 'prevent', 'definition': 'to stop something from happening', 'example': 'Vaccines prevent diseases.'},
    {'word': 'process', 'definition': 'a series of actions to achieve something', 'example': 'Learning a language is a long process.'},
    {'word': 'progress', 'definition': 'improvement or development', 'example': 'She has made great progress in English.'},
    {'word': 'property', 'definition': 'something that belongs to someone', 'example': 'This house is my property.'},
    {'word': 'protect', 'definition': 'to keep safe from harm', 'example': 'We must protect the environment.'},
    {'word': 'provide', 'definition': 'to give what is needed', 'example': 'The school provides free lunch.'},
    {'word': 'purpose', 'definition': 'the reason for doing something', 'example': 'What is the purpose of this meeting?'},
    {'word': 'quality', 'definition': 'how good or bad something is', 'example': 'The quality of this product is high.'},
    {'word': 'realize', 'definition': 'to understand something clearly', 'example': 'I didn\'t realize you were here.'},
    {'word': 'recommend', 'definition': 'to suggest something as good', 'example': 'Can you recommend a good restaurant?'},
    {'word': 'reduce', 'definition': 'to make something less', 'example': 'We need to reduce waste.'},
    {'word': 'refer', 'definition': 'to mention or speak about something', 'example': 'He referred to the report in his speech.'},
    {'word': 'reflect', 'definition': 'to show an image or to think carefully', 'example': 'The mirror reflects your face.'},
    {'word': 'refuse', 'definition': 'to say no to something', 'example': 'She refused to answer the question.'},
    {'word': 'regret', 'definition': 'to feel sorry about something', 'example': 'I regret not studying harder.'},
    {'word': 'relate', 'definition': 'to show a connection between things', 'example': 'How does this relate to our topic?'},
    {'word': 'remove', 'definition': 'to take something away', 'example': 'Please remove your shoes.'},
    {'word': 'replace', 'definition': 'to put something new in the place of something old', 'example': 'We need to replace the batteries.'},
    {'word': 'require', 'definition': 'to need something', 'example': 'This job requires experience.'},
    {'word': 'respond', 'definition': 'to answer', 'example': 'He didn\'t respond to my email.'},
    {'word': 'result', 'definition': 'something that happens because of something else', 'example': 'The result was surprising.'},
    {'word': 'risk', 'definition': 'the possibility of something bad happening', 'example': 'There is a risk of injury.'},
    {'word': 'satisfy', 'definition': 'to make someone happy by giving them what they want', 'example': 'The meal satisfied my hunger.'},
    {'word': 'select', 'definition': 'to choose', 'example': 'Select the correct answer.'},
    {'word': 'similar', 'definition': 'almost the same', 'example': 'These two cars are very similar.'},
    {'word': 'solution', 'definition': 'the answer to a problem', 'example': 'We found a solution to the problem.'},
    {'word': 'source', 'definition': 'where something comes from', 'example': 'The source of the river is in the mountains.'},
    {'word': 'specific', 'definition': 'clearly defined or identified', 'example': 'Can you be more specific?'},
    {'word': 'strength', 'definition': 'the quality of being strong', 'example': 'She has great strength.'},
    {'word': 'suggest', 'definition': 'to offer an idea or plan', 'example': 'He suggested going for a walk.'},
    {'word': 'support', 'definition': 'to help or encourage', 'example': 'My family supports me.'},
    {'word': 'suppose', 'definition': 'to think that something is likely', 'example': 'I suppose you are right.'},
    {'word': 'survive', 'definition': 'to continue to live after a difficult event', 'example': 'They survived the storm.'},
    {'word': 'tend', 'definition': 'to usually do something', 'example': 'I tend to wake up early.'},
    {'word': 'theory', 'definition': 'an idea that explains something', 'example': 'The theory is difficult to understand.'},
    {'word': 'tradition', 'definition': 'a custom passed from one generation to another', 'example': 'It is a family tradition.'},
    {'word': 'translate', 'definition': 'to change words into another language', 'example': 'Can you translate this sentence?'},
    {'word': 'variety', 'definition': 'a number of different types of things', 'example': 'There is a wide variety of food.'},
    {'word': 'waste', 'definition': 'to use something carelessly', 'example': 'Don\'t waste your time.'},
    {'word': 'worth', 'definition': 'having value', 'example': 'This painting is worth a lot of money.'}
]

advanced_words = [
    {'word': 'abandon', 'definition': 'to leave behind or give up', 'example': 'They had to abandon the project.'},
    {'word': 'abstract', 'definition': 'existing in thought but not having a physical form', 'example': 'Love is an abstract concept.'},
    {'word': 'acquire', 'definition': 'to get or gain something', 'example': 'He acquired a lot of knowledge at university.'},
    {'word': 'adapt', 'definition': 'to change to fit new conditions', 'example': 'Animals adapt to their environment.'},
    {'word': 'adequate', 'definition': 'enough or satisfactory', 'example': 'The food was adequate for everyone.'},
    {'word': 'advocate', 'definition': 'to support or argue for something', 'example': 'She is an advocate for human rights.'},
    {'word': 'ambiguous', 'definition': 'having more than one possible meaning', 'example': 'His answer was ambiguous.'},
    {'word': 'analyze', 'definition': 'to study something carefully', 'example': 'Scientists analyze the results.'},
    {'word': 'anticipate', 'definition': 'to expect or look forward to something', 'example': 'We anticipate good results.'},
    {'word': 'apparent', 'definition': 'clearly visible or understood', 'example': 'It was apparent that he was tired.'},
    {'word': 'arbitrary', 'definition': 'based on random choice or personal whim', 'example': 'The rules seemed arbitrary and unfair.'},
    {'word': 'articulate', 'definition': 'able to express thoughts clearly', 'example': 'She is very articulate in her arguments.'},
    {'word': 'assert', 'definition': 'to state something confidently', 'example': 'He asserted his innocence.'},
    {'word': 'assess', 'definition': 'to evaluate or estimate', 'example': 'We need to assess the damage.'},
    {'word': 'assume', 'definition': 'to take for granted without proof', 'example': 'We cannot assume he is guilty.'},
    {'word': 'authentic', 'definition': 'genuine or real', 'example': 'This is an authentic antique.'},
    {'word': 'authority', 'definition': 'power to give orders or make decisions', 'example': 'The police have authority to arrest.'},
    {'word': 'autonomous', 'definition': 'independent and self-governing', 'example': 'The region became autonomous.'},
    {'word': 'benevolent', 'definition': 'kind and generous', 'example': 'The benevolent king helped the poor.'},
    {'word': 'bias', 'definition': 'prejudice in favor of or against something', 'example': 'The article showed clear bias.'},
    {'word': 'brevity', 'definition': 'concise and exact use of words', 'example': 'The speech was noted for its brevity.'},
    {'word': 'candid', 'definition': 'truthful and straightforward', 'example': 'She gave a candid interview.'},
    {'word': 'capacity', 'definition': 'the maximum amount something can contain', 'example': 'The stadium has a capacity of 50,000.'},
    {'word': 'catastrophic', 'definition': 'involving or causing sudden great damage', 'example': 'The earthquake was catastrophic.'},
    {'word': 'cautious', 'definition': 'careful to avoid potential problems', 'example': 'Be cautious when crossing the road.'},
    {'word': 'coherent', 'definition': 'logical and well-organized', 'example': 'His argument was coherent.'},
    {'word': 'collaborate', 'definition': 'to work together', 'example': 'The scientists collaborated on the research.'},
    {'word': 'compelling', 'definition': 'evoking interest or attention', 'example': 'The evidence was compelling.'},
    {'word': 'comprehensive', 'definition': 'complete and including everything', 'example': 'The report was comprehensive.'},
    {'word': 'conceive', 'definition': 'to form an idea or plan', 'example': 'He conceived a new business strategy.'},
    {'word': 'concurrent', 'definition': 'happening at the same time', 'example': 'The two events were concurrent.'},
    {'word': 'condemn', 'definition': 'to express strong disapproval', 'example': 'The government condemned the attack.'},
    {'word': 'confidential', 'definition': 'intended to be kept secret', 'example': 'This information is confidential.'},
    {'word': 'conform', 'definition': 'to comply with rules or standards', 'example': 'You must conform to the regulations.'},
    {'word': 'consensus', 'definition': 'general agreement', 'example': 'The committee reached a consensus.'},
    {'word': 'consequent', 'definition': 'following as a result', 'example': 'The consequent changes were significant.'},
    {'word': 'conserve', 'definition': 'to protect from harm or destruction', 'example': 'We must conserve our natural resources.'},
    {'word': 'considerable', 'definition': 'large in size or amount', 'example': 'The project required considerable effort.'},
    {'word': 'consistent', 'definition': 'unchanging in nature or standard', 'example': 'Her work is consistently good.'},
    {'word': 'conspicuous', 'definition': 'clearly visible or noticeable', 'example': 'The error was conspicuous.'},
    {'word': 'exalt', 'definition': 'to praise highly', 'example': 'They exalted his achievements.'},
    {'word': 'exemplify', 'definition': 'to be a typical example', 'example': 'This case exemplifies the problem.'},
    {'word': 'exhaustive', 'definition': 'including all possibilities', 'example': 'The search was exhaustive.'},
    {'word': 'explicit', 'definition': 'stated clearly and in detail', 'example': 'The instructions were explicit.'},
    {'word': 'exploit', 'definition': 'to make use of', 'example': 'They exploited the opportunity.'},
    {'word': 'exponent', 'definition': 'a person who supports an idea', 'example': 'He is an exponent of modern art.'},
    {'word': 'expunge', 'definition': 'to erase or remove', 'example': 'The record was expunged.'},
    {'word': 'extol', 'definition': 'to praise enthusiastically', 'example': 'They extolled his virtues.'},
    {'word': 'extract', 'definition': 'to remove or take out', 'example': 'They extracted the information.'},
    {'word': 'extricate', 'definition': 'to free from difficulty', 'example': 'They extricated themselves from the situation.'},
    {'word': 'exuberant', 'definition': 'full of energy and excitement', 'example': 'The children were exuberant.'},
    {'word': 'fabricate', 'definition': 'to invent or make up', 'example': 'The story was fabricated.'},
    {'word': 'facilitate', 'definition': 'to make easier', 'example': 'The new system facilitates communication.'},
    {'word': 'fallacious', 'definition': 'based on a mistaken belief', 'example': 'The argument was fallacious.'},
    {'word': 'fallible', 'definition': 'capable of making mistakes', 'example': 'Humans are fallible.'},
    {'word': 'fathom', 'definition': 'to understand after much thought', 'example': 'I cannot fathom his motives.'},
    {'word': 'feasible', 'definition': 'possible to do easily', 'example': 'The plan is feasible.'},
    {'word': 'fervent', 'definition': 'having great intensity of feeling', 'example': 'She is a fervent supporter.'},
    {'word': 'fickle', 'definition': 'changing frequently', 'example': 'The weather is fickle.'},
    {'word': 'finite', 'definition': 'having limits', 'example': 'Resources are finite.'},
    {'word': 'flourish', 'definition': 'to grow or develop well', 'example': 'The business flourished.'},
    {'word': 'fluctuate', 'definition': 'to change continuously', 'example': 'Prices fluctuate daily.'},
    {'word': 'forbear', 'definition': 'to refrain from doing something', 'example': 'He forbore from commenting.'},
    {'word': 'forgo', 'definition': 'to go without', 'example': 'She decided to forgo the opportunity.'},
    {'word': 'embark', 'definition': 'to begin a course of action', 'example': 'They embarked on a new project.'},
    {'word': 'embody', 'definition': 'to represent in physical form', 'example': 'The statue embodies the spirit of freedom.'},
    {'word': 'emerge', 'definition': 'to come into existence', 'example': 'A new problem emerged.'},
    {'word': 'empirical', 'definition': 'based on observation or experience', 'example': 'The theory has empirical support.'},
    {'word': 'encompass', 'definition': 'to include comprehensively', 'example': 'The study encompasses many topics.'},
    {'word': 'endeavor', 'definition': 'to try hard to achieve something', 'example': 'They endeavored to succeed.'},
    {'word': 'endorse', 'definition': 'to declare support for', 'example': 'The committee endorsed the plan.'},
    {'word': 'endure', 'definition': 'to suffer patiently', 'example': 'They endured many hardships.'},
    {'word': 'enforce', 'definition': 'to compel observance of', 'example': 'The police enforce the law.'},
    {'word': 'engage', 'definition': 'to participate or become involved', 'example': 'She engaged in the discussion.'},
    {'word': 'enhance', 'definition': 'to increase or improve', 'example': 'The software enhances productivity.'},
    {'word': 'enigma', 'definition': 'a person or thing that is mysterious', 'example': 'He remains an enigma.'},
    {'word': 'enlighten', 'definition': 'to give greater knowledge', 'example': 'The book enlightened the readers.'},
    {'word': 'enrich', 'definition': 'to improve the quality', 'example': 'The experience enriched their lives.'},
    {'word': 'ensue', 'definition': 'to happen as a result', 'example': 'Chaos ensued after the announcement.'},
    {'word': 'entail', 'definition': 'to involve as a necessary part', 'example': 'The job entails long hours.'},
    {'word': 'entice', 'definition': 'to attract by offering pleasure', 'example': 'The offer enticed many customers.'},
    {'word': 'entity', 'definition': 'a thing with distinct existence', 'example': 'The company is a legal entity.'},
    {'word': 'enumerate', 'definition': 'to mention things one by one', 'example': 'She enumerated the reasons.'},
    {'word': 'envisage', 'definition': 'to contemplate or conceive', 'example': 'They envisaged a better future.'},
    {'word': 'ephemeral', 'definition': 'lasting for a very short time', 'example': 'The trend was ephemeral.'},
    {'word': 'epitome', 'definition': 'a perfect example of something', 'example': 'She is the epitome of grace.'},
    {'word': 'equate', 'definition': 'to consider as the same', 'example': 'Don\'t equate money with happiness.'},
    {'word': 'eradicate', 'definition': 'to destroy completely', 'example': 'They tried to eradicate the disease.'},
    {'word': 'erroneous', 'definition': 'wrong or incorrect', 'example': 'The report contained erroneous data.'},
    {'word': 'erudite', 'definition': 'having great knowledge', 'example': 'He is an erudite scholar.'},
    {'word': 'escalate', 'definition': 'to increase rapidly', 'example': 'The conflict escalated.'},
    {'word': 'espouse', 'definition': 'to adopt or support', 'example': 'They espoused new ideas.'},
    {'word': 'essence', 'definition': 'the fundamental nature', 'example': 'The essence of the problem is clear.'},
    {'word': 'esteem', 'definition': 'respect and admiration', 'example': 'He is held in high esteem.'},
    {'word': 'eternal', 'definition': 'lasting forever', 'example': 'They promised eternal love.'},
    {'word': 'ethical', 'definition': 'relating to moral principles', 'example': 'The decision was ethical.'},
    {'word': 'evoke', 'definition': 'to bring to mind', 'example': 'The music evoked memories.'},
    {'word': 'exacerbate', 'definition': 'to make worse', 'example': 'The situation was exacerbated.'},
    {'word': 'domain', 'definition': 'an area of territory or knowledge', 'example': 'This is outside my domain.'},
    {'word': 'domestic', 'definition': 'relating to the home or family', 'example': 'Domestic violence is a serious issue.'},
    {'word': 'dominate', 'definition': 'to have control over', 'example': 'The company dominates the market.'},
    {'word': 'dormant', 'definition': 'temporarily inactive', 'example': 'The volcano is dormant.'},
    {'word': 'drastic', 'definition': 'likely to have a strong effect', 'example': 'They took drastic measures.'},
    {'word': 'dubious', 'definition': 'doubtful or questionable', 'example': 'The claim seemed dubious.'},
    {'word': 'duplicate', 'definition': 'to make an exact copy', 'example': 'They duplicated the document.'},
    {'word': 'dynamic', 'definition': 'characterized by constant change', 'example': 'The situation is dynamic.'},
    {'word': 'eccentric', 'definition': 'unconventional or strange', 'example': 'He had an eccentric personality.'},
    {'word': 'eclectic', 'definition': 'deriving from various sources', 'example': 'She has eclectic tastes in music.'},
    {'word': 'elaborate', 'definition': 'involving many carefully arranged parts', 'example': 'They made elaborate plans.'},
    {'word': 'elicit', 'definition': 'to draw out a response', 'example': 'The question elicited a strong reaction.'},
    {'word': 'elude', 'definition': 'to escape from or avoid', 'example': 'The answer eluded them.'},
    {'word': 'delineate', 'definition': 'to describe or portray precisely', 'example': 'The report delineated the problems.'},
    {'word': 'denote', 'definition': 'to be a sign of something', 'example': 'The symbol denotes danger.'},
    {'word': 'denounce', 'definition': 'to publicly declare to be wrong', 'example': 'They denounced the violence.'},
    {'word': 'depict', 'definition': 'to represent by drawing or painting', 'example': 'The painting depicts a battle.'},
    {'word': 'deplete', 'definition': 'to reduce in number or quantity', 'example': 'The resources were depleted.'},
    {'word': 'derive', 'definition': 'to obtain from a source', 'example': 'The word derives from Latin.'},
    {'word': 'designate', 'definition': 'to officially assign a role', 'example': 'He was designated as leader.'},
    {'word': 'despise', 'definition': 'to feel contempt for', 'example': 'She despised dishonesty.'},
    {'word': 'detain', 'definition': 'to keep in custody', 'example': 'The police detained the suspect.'},
    {'word': 'deter', 'definition': 'to discourage from acting', 'example': 'The warning deterred further attempts.'},
    {'word': 'deteriorate', 'definition': 'to become progressively worse', 'example': 'The situation deteriorated.'},
    {'word': 'deviate', 'definition': 'to depart from a course', 'example': 'The project deviated from the plan.'},
    {'word': 'devise', 'definition': 'to plan or invent', 'example': 'They devised a new strategy.'},
    {'word': 'devote', 'definition': 'to give time or effort to something', 'example': 'She devoted herself to research.'},
    {'word': 'differentiate', 'definition': 'to recognize what makes something different', 'example': 'It\'s hard to differentiate between them.'},
    {'word': 'diffuse', 'definition': 'to spread over a wide area', 'example': 'The light diffused through the room.'},
    {'word': 'digress', 'definition': 'to leave the main subject', 'example': 'He tended to digress from the topic.'},
    {'word': 'dilemma', 'definition': 'a difficult choice between two options', 'example': 'She faced a moral dilemma.'},
    {'word': 'diminish', 'definition': 'to make or become less', 'example': 'The problem diminished over time.'},
    {'word': 'discern', 'definition': 'to recognize or understand', 'example': 'It was hard to discern the truth.'},
    {'word': 'disclose', 'definition': 'to make known', 'example': 'He disclosed the information.'},
    {'word': 'discrete', 'definition': 'separate and distinct', 'example': 'The problems were discrete.'},
    {'word': 'discriminate', 'definition': 'to recognize a distinction', 'example': 'The test discriminates between levels.'},
    {'word': 'displace', 'definition': 'to take the place of', 'example': 'New technology displaced old methods.'},
    {'word': 'dispose', 'definition': 'to get rid of', 'example': 'They disposed of the waste.'},
    {'word': 'dispute', 'definition': 'to argue about', 'example': 'They disputed the claim.'},
    {'word': 'disrupt', 'definition': 'to interrupt or break up', 'example': 'The storm disrupted the event.'},
    {'word': 'disseminate', 'definition': 'to spread widely', 'example': 'They disseminated the information.'},
    {'word': 'dissipate', 'definition': 'to disappear or scatter', 'example': 'The fog dissipated.'},
    {'word': 'distort', 'definition': 'to change the shape or sound', 'example': 'The mirror distorted the image.'},
    {'word': 'divert', 'definition': 'to change direction', 'example': 'They diverted the traffic.'},
    {'word': 'divulge', 'definition': 'to make known something secret', 'example': 'He refused to divulge the source.'},
    {'word': 'embark', 'definition': 'to begin a course of action', 'example': 'They embarked on a new project.'},
    {'word': 'doctrine', 'definition': 'a belief or set of beliefs', 'example': 'The political doctrine was clear.'},  
    {'word': 'constitute', 'definition': 'to be the parts or materials that form something', 'example': 'Women constitute 50 percent of the workforce.'},
    {'word': 'constrain', 'definition': 'to limit or restrict', 'example': 'Time constraints prevented further research.'},
    {'word': 'contemplate', 'definition': 'to think deeply about something', 'example': 'He contemplated his future.'},
    {'word': 'contemporary', 'definition': 'belonging to the present time', 'example': 'Contemporary art is on display.'},
    {'word': 'contradict', 'definition': 'to say the opposite of something', 'example': 'His statement contradicts the evidence.'},
    {'word': 'contrary', 'definition': 'opposite in nature or direction', 'example': 'The results were contrary to expectations.'},
    {'word': 'controversial', 'definition': 'causing disagreement or discussion', 'example': 'The decision was controversial.'},
    {'word': 'convene', 'definition': 'to come together for a meeting', 'example': 'The committee will convene next week.'},
    {'word': 'conventional', 'definition': 'following traditional methods', 'example': 'They used conventional farming methods.'},
    {'word': 'convey', 'definition': 'to communicate or make known', 'example': 'The message conveyed important information.'},
    {'word': 'conviction', 'definition': 'a strong belief or opinion', 'example': 'She spoke with conviction.'},
    {'word': 'coordinate', 'definition': 'to organize different elements', 'example': 'They coordinated the rescue effort.'},
    {'word': 'correlate', 'definition': 'to have a mutual relationship', 'example': 'Smoking correlates with lung cancer.'},
    {'word': 'corroborate', 'definition': 'to confirm or support with evidence', 'example': 'The witness corroborated his story.'},
    {'word': 'counterpart', 'definition': 'a person or thing that corresponds to another', 'example': 'The American president met his Russian counterpart.'},
    {'word': 'credible', 'definition': 'able to be believed', 'example': 'The witness was credible.'},
    {'word': 'criteria', 'definition': 'standards by which something is judged', 'example': 'The selection criteria were strict.'},
    {'word': 'crucial', 'definition': 'extremely important', 'example': 'This is a crucial decision.'},
    {'word': 'culminate', 'definition': 'to reach the highest point', 'example': 'The project culminated in success.'},
    {'word': 'cumulative', 'definition': 'increasing by successive additions', 'example': 'The cumulative effect was significant.'},
    {'word': 'curtail', 'definition': 'to reduce or limit', 'example': 'They had to curtail their spending.'},
    {'word': 'daunting', 'definition': 'seeming difficult to deal with', 'example': 'The task seemed daunting.'},
    {'word': 'debate', 'definition': 'to discuss a topic formally', 'example': 'They debated the issue for hours.'},
    {'word': 'decisive', 'definition': 'settling an issue', 'example': 'The evidence was decisive.'},
    {'word': 'decline', 'definition': 'to become smaller or fewer', 'example': 'Sales declined last year.'},
    {'word': 'dedicate', 'definition': 'to commit to a particular purpose', 'example': 'She dedicated her life to science.'},
    {'word': 'deduce', 'definition': 'to reach a conclusion by reasoning', 'example': 'From the evidence, we can deduce the truth.'},
    {'word': 'deem', 'definition': 'to consider or judge', 'example': 'The project was deemed successful.'},
    {'word': 'defer', 'definition': 'to postpone or delay', 'example': 'They decided to defer the decision.'},
    {'word': 'deficient', 'definition': 'not having enough of something', 'example': 'The diet was deficient in vitamins.'},
    {'word': 'definitive', 'definition': 'conclusive or final', 'example': 'This is the definitive answer.'},
    {'word': 'delegate', 'definition': 'to give a particular job to someone', 'example': 'She delegated the task to her assistant.'},
    {'word': 'deliberate', 'definition': 'done consciously and intentionally', 'example': 'It was a deliberate choice.'},
    {'word': 'delineate', 'definition': 'to describe or portray precisely', 'example': 'The report delineated the problems.'},
    {'word': 'denote', 'definition': 'to be a sign of something', 'example': 'The symbol denotes danger.'},
    {'word': 'denounce', 'definition': 'to publicly declare to be wrong', 'example': 'They denounced the violence.'},
    {'word': 'depict', 'definition': 'to represent by drawing or painting', 'example': 'The painting depicts a battle.'},
    {'word': 'deplete', 'definition': 'to reduce in number or quantity', 'example': 'The resources were depleted.'},
    {'word': 'deploy', 'definition': 'to bring into effective action', 'example': 'They deployed new technology.'},
] 